### ISSUE TITLE
Resolve response references for OpenAPI 3.0 (#/components/responses instead of #/responses)

### ISSUE THREAD

**Issue by christian-knecht** [kogosoftwarellc/open-api#289] opened 2019-01-03 21:46 UTC
# The problem

When defining reusable responses within the components object of the OpenAPI Document as specified in the [Open API 3.0.2 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#components-object) the schema validation fails for Open API version > 3.0.0. The response references for V2.0 are resolved well.

Affected package: openapi-framework (util function resolveResponseRefs)

# Example

Following example spec fails when using the express-openapi middleware.

> express-openapi: Invalid response $ref or definition not found in apiDoc.responses: #/components/responses/Error

## The Open API Spec
```json
{
  "openapi": "3.0.2",
  "info": {
    "version": "2.0.0",
    "title": "Basic Usage Example"
  },
  "paths": {},
  "components": {
    "responses": {
        "Error": {
          "description": "An error occurred",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "error"
                ],
                "properties": {
                  "error": {
                    "type": "object",
                    "required": [
                      "message"
                    ],
                    "properties": {
                      "message": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
  }
}
```

## Path Handler

```javascript
/*******************************************************************
 *   paths/config.js
 *******************************************************************/
module.exports = function (config) {
     let operations = {
          GET
     };

     operations.GET.apiDoc = {
          summary: 'Returns config.',
          operationId: 'getConfig',
          parameters: [],
          responses: {
               200: {
                    description: 'Success',
                    schema: {
                         $ref: '#/components/schemas/Config'
                    }
               },
               default: {
                    $ref: '#/components/responses/Error'
               }
          }
     };

     function GET(req, res, next) {
          res.validateAndSend(200, config);
     }

     return operations;
};
```
# Affected Open API util function

The resolveResponseRefs function tries to get the definition from apiDoc.responses (#/responses) instead of apiDoc.components.responses (#/components/responses).

```javascript
/*******************************************************************
 *   /node_modules/openapi-framework/dist/src/util.js
 *******************************************************************/
function resolveResponseRefs(framework, responses, apiDoc, route) {
    return Object.keys(responses).reduce(function (resolvedResponses, responseCode) {
        var response = responses[responseCode];
        if (typeof response.$ref === 'string') {
            var match = RESPONSE_REF_REGEX.exec(response.$ref);
            var definition = match && (apiDoc.responses || {})[match[1]];
            if (!definition) {
                throw new Error(framework.name + ": Invalid response $ref or definition not found in apiDoc.responses: " + response.$ref);
            }
            resolvedResponses[responseCode] = definition;
        }
        else {
            resolvedResponses[responseCode] = response;
        }
        return resolvedResponses;
    }, {});
}
```

My suggestion would be to differentiate between the different API versions and handle the resolving accordingly:

```javascript
var apiVersion = apiDoc.swagger ? apiDoc.swagger : apiDoc.openapi;
var responses = apiVersion === "2.0" ? apiDoc.responses : apiDoc.components.responses;
```

**Comment by mbsimonovic** [comment] 2019-01-03 22:00
isn't this a duplicate of https://github.com/kogosoftwarellc/open-api/issues/280 ?

**Comment by christian-knecht** [comment] 2019-01-03 22:13
As far as I understood you get the error message in #280 during the POST call. This error is thrown during schema validation at server startup. It seems that different packages or functions are affected.

**Comment by mbsimonovic** [comment] 2019-01-03 22:14
hm, you're right, seemed like the same problem at first

**Comment by jsdevel** [comment] 2019-01-03 22:31
@christian-knecht please submit a PR

**Closed** 2019-01-08 17:34 UTC
Labels: OpenAPIV3
