### ISSUE TITLE
File upload not working

### ISSUE THREAD

**Issue by hkors** [kogosoftwarellc/open-api#29] opened 2016-03-30 09:02 UTC
Hello,

I have an endpoint documented like this:

```
post.apiDoc = {
    description: 'Upload an image for the category',
    operationId: 'uploadCategoryImage',
    tags: ['categories'],
    consumes: ['multipart/form-data'],
    parameters: [
        {
            name: 'image',
            in: 'formData',
            type: 'file',
            description: 'An image for this category',
            required: true
        }
    ],
    responses: {
        201: {
            description: 'Image successfully uploaded'
        },
        default: {
            description: 'Unexpected error',
            schema: {
                $ref: '#/definitions/Error'
            }
        }
    }
};
```

In the Swagger UI, a file upload thing is visible:

![swagger](https://cloud.githubusercontent.com/assets/17003285/14137171/eace27ee-f666-11e5-8d39-0b368c67b0f3.png)

However, I keep getting this error when I send a file:

```
{
    path: 'image',
    errorCode: 'required.openapi.validation',
    message: 'instance requires property "image"',
    location: 'body'
}
```

I do have a `Content-Type: multipart/form-data` header in the HTTP request.
Am I doing something wrong or is it a bug?

**Comment by hkors** [comment] 2016-03-30 09:23
I can now receive the file by adding ```
  'x-express-openapi-disable-validation-middleware': true``` to this documentation, but I suppose this shouldn't be the solution...

**Comment by jsdevel** [comment] 2016-03-30 15:55
@hkors there's currently no support for file uploads.  It would be great if you could propose a solution.  Most swagger frameworks that I've seen don't handle this very well.  I'd love to be one of the first!

**Comment by mghignet** [comment] 2016-10-04 12:46
Hi!

The issue should be fixed now, I had the same problem.
See https://github.com/kogosoftwarellc/express-openapi/pull/55

**Comment by jsdevel** [comment] 2016-10-04 16:39
Thanks @mghignet !  I've published #55 as `v0.30.0`.  If you have the time, could you add a sample project to the test suite showing a file upload example?

**Comment by jsdevel** [comment] 2016-10-04 16:40
@hkors if you're able to try again with the latest version it would be appreciated.  I'll leave this issue open until we have confirmation that file uploads work.

**Comment by mghignet** [comment] 2016-10-05 13:33
Actually the bug is still present.
The issue is that we need to validate the presence of some fields (typically, a file) in formData, but it's not as easy as for a body or a query string.
The only workaround I've found is to remove the "required" property from formData parameters.

**Comment by mghignet** [comment] 2016-10-05 14:06
https://github.com/kogosoftwarellc/express-openapi-validation/commit/0096f84256dd5448c6b21c328d69bf0139194b13
I've commented on this.
The "quick and dirty" solution I see would be to remote the piece of code I commented to disable errors for formData fields, since we're not able to validate them correctly.
It means "required" property (and maybe some other ones) would be ineffective.
What do you think?

**Comment by jsdevel** [comment] 2017-01-25 06:17
@mghignet sorry for the late reply.  Holidays and election happened here in the states.  Barely getting back in the swing of things.

Whatever we need to do to get file uploads working, as long as the tests pass, I say we do it!  Can you submit a PR?

**Comment by alrik** [comment] 2018-01-02 23:08
I got it to work with `multer` and a little tweak. Hopefully the following examples will be helpful for some people.

Multer is a multipart form-data handling middleware. by default it stores the upload to `req.file` or `req.files`. The express-openapi-validation logic is looking for defined files in `req.body`. So we need to copy the file upload to the expected position.

```js
expressOpenapi.initialize({
  consumesMiddleware: {
    // Allow for single file upload (filename: 'file')
    'multipart/form-data'(req, res, next) {
      multer().single('file')(req, res, (err) => {
        if (err) return next(err);
        req.body.file = req.file;
        next();
      });
    }

    // Allow for any file upload
    'multipart/form-data'(req, res, next) {
      multer().any()(req, res, (err) => {
        if (err) return next(err);
        req.files.forEach(f => req.body[f.fieldname] = f);
        next();
      });
    }
  },
});
```

**Comment by jsdevel** [comment] 2018-01-02 23:13
Nice @alrik !  Can you by chance update the README with this example, and possibly create a test (i.e. can you add `multer` as a `devDependency` to show that it works)?

**Comment by alrik** [comment] 2018-01-03 08:54
Hey @jsdevel sure. I'll add an example to the readme and add some tests when i got some spare time. Could you assign me the issue, so that i don't forget about it?

**Comment by jsdevel** [comment] 2018-01-03 15:35
@alrik looks like I'm unable to assign to non-project collaborators.  If you own an issue, I can assign it to you.  Want to open a new issue here about a missing example in the README for file uploads?  I should be able to assign that to you.

**Comment by simpgeek** [comment] 2018-05-25 14:43
I submit that this issue is addressed satisfactorily by #105

**Comment by jsdevel** [comment] 2018-05-25 14:55
Agreed.  Thanks @simpgeek!  @hkors let us know if you disagree.

**Closed by jsdevel** 2018-05-25 14:55 UTC
Labels: express-openapi

**Comment by mbsimonovic** [comment] 2018-12-31 07:50
i'm getting an error trying to test this with curl. The spec is:

```
    /upload/:
        post:
            summary: Create NEW files
            operationId: upload
            requestBody:
                required: true
                content:
                    multipart/form-data:
                        schema:
                            type: object
                            properties:
                                docs:
                                    type: array
                                    items:
                                        type: string
                                        format: binary

```
and express-openapi is initialised as suggested:
```
 'multipart/form-data'(req, res, next) {
            multer().any()(req, res, (err) => {
                if (err) return next(err);
                req.files.forEach(f => req.body[f.fieldname] = f);
                return next(); // this executes correctly
            });
        }
```

Hitting the app with curl:
`curl   "http://localhost:3000/upload/" -H "accept: */*" -H "Content-Type: multipart/form-data" -F docs=@package.json `, fails with the following error (the endpoint never gets called):

```
Unsupported Content-Type multipart/form-data; boundary=------------------------2a07fe1e704ec1f5
```

The same happens with superagent/supertest and postman. Any hints?

**Comment by jsdevel** [comment] 2018-12-31 08:07
@mbsimonovic please file a new issue.  that appears to be related to V3 which wasn't published at the time this issue was created.
