### ISSUE TITLE
Fix PARAMETER and RESPONSE regexps

### ISSUE THREAD

**Issue by wingedfox** [kogosoftwarellc/open-api#185] opened 2018-08-28 14:03 UTC
https://github.com/kogosoftwarellc/open-api/blob/43e7baba9efa5503a47891aa8d38a53a0a19af68/packages/openapi-framework/src/util.ts#L6
https://github.com/kogosoftwarellc/open-api/blob/43e7baba9efa5503a47891aa8d38a53a0a19af68/packages/openapi-framework/src/util.ts#L8

There are multiple issues with these lines

1. OAS 3.0 defines parameters and responses under `#/components/`
2. Spec downconverted from OAS 3.0 to 2.0 with https://github.com/lucybot/api-spec-converter moves definitions under `#/x-components/ namespace

**Comment by jsdevel** [comment] 2018-08-28 16:58
@wingedfox thanks for reporting this.  Can you raise a PR with the fix?

**Comment by wingedfox** [comment] 2018-08-28 17:19
I'd check how to fix that, but it seems to be a quite complex PR.
Actually, I do not see such params/responses in the supplied args in the corresponding functions.

**Comment by moravcik** [comment] 2018-09-07 10:13
I am also having this issue, the problem is not only RESPONSE_REF_REGEX, but also this line:
https://github.com/kogosoftwarellc/open-api/blob/43e7baba9efa5503a47891aa8d38a53a0a19af68/packages/openapi-framework/src/util.ts#L230

which accesses `apiDoc.responses` directly

**Comment by jsdevel** [comment] 2018-09-07 18:26
@moravcik if you could raise a PR it would be appreciated.  Right now OpenAPIv3 support is entirely community driven.

**Comment by jsdevel** [comment] 2018-12-17 16:33
this is fixed in https://github.com/kogosoftwarellc/open-api/pull/271

**Closed by jsdevel** 2018-12-17 16:33 UTC
Labels: OpenAPIV3
